# Generated by Django 4.2.28 on 2026-02-15 23:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data_modeling", "0010_remove_edge_unique_within_dag_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="edge",
            name="dag_id",
        ),
    ]
