# Generated by Django 4.2.28 on 2026-03-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1036_hogflowrevision_hogflow_active_revision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hogflowrevision",
            name="deleted_action_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="hogflowrevision",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
